import SideBar from "@/components/SideBar";
import "@/styles/globals.css";
import Login from "@/components/Login";
import { getServerSession } from "next-auth";
import Providers from "@/components/Providers";
// import { Providers } from "@/components/Providers";

export const metadata = {
  title: "ChatGPT",
  description: "Generated by create next app",
};

/* chatgpt aplikey */
// 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

type Props = {
  children: React.ReactNode;
};
export default async function RootLayout({ children }: Props) {
  const session = await getServerSession();

  // console.log(session);
  return (
    <html lang="en">
      <body>
        <Providers session={session} >
          {!session ? (
            <Login />
          ) : (
            <div className="flex">
              <div className="bg-[#202123] max-w-xs h-screen overflow-y-auto md:min-w-[20rem] ">
                <SideBar/>
              </div>
              <div className="bg-[#343541] flex-1">{children}</div>
            </div>
          )}
        </Providers>
      </body>
    </html>
  );
}
