import SideBar from "@/components/SideBar";
import "@/styles/globals.css";
import Login from "@/components/Login";
import { getServerSession } from "next-auth";
import Providers from "@/components/Providers";
import ClientProvider from "@/components/ClientProvider";
import { authOptions } from "@/pages/api/auth/[...nextauth]";

export const metadata = {
  title: "ChatGPT",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
};
export default async function RootLayout({ children }: Props) {
  const session = await getServerSession(authOptions);
  
  return (
    <html lang="en">
      <body>
        <Providers session={session}>
          {!session ? (
            <Login />
          ) : (
            <div className="flex">
              <div className="bg-[#202123] max-w-xs h-screen overflow-y-auto md:min-w-[20rem] ">
                <SideBar />
              </div>
              {/* Toaster in it*/}
              <ClientProvider />
              <div className="bg-[#343541] flex-1">{children}</div>
            </div>
          )}
        </Providers>
      </body>
    </html>
  );
}
